apiVersion: v1
kind: Secret
metadata:
  name: insights-bot-secrets
  namespace: default
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: ""
  OPENAI_API_SECRET: ""
  DB_CONNECTION_STR: ""
  REDIS_PASSWORD: ""
